name: geometric
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - biopython=1.78=py38h25fe258_1
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - freetype=2.10.4=h5ab3b9f_0
  - icu=67.1=he1b5a44_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py38h82cb98a_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.2=py38hff7bd54_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=h7b6447c_0
  - pillow=8.1.0=py38he98fc37_0
  - pip=20.3.3=py38h06a4308_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda10.1.243_cudnn7.6.3_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu101
  - tornado=6.1=py38h25fe258_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - ase==3.21.1
    - chardet==4.0.0
    - googledrivedownloader==0.4
    - h5py==3.1.0
    - idna==2.10
    - isodate==0.6.0
    - jinja2==2.11.3
    - joblib==1.0.0
    - llvmlite==0.35.0
    - markupsafe==1.1.1
    - numba==0.52.0
    - pandas==1.2.1
    - python-louvain==0.15
    - pytz==2020.5
    - rdflib==5.0.0
    - requests==2.25.1
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - threadpoolctl==2.1.0
    - torch-cluster==1.5.8
    - torch-geometric==1.6.3
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - tqdm==4.56.0
    - urllib3==1.26.3
prefix: /home/miniconda3/envs/geometric
